title: Greg's blog
description: Tinkering with the web. Pragmatic and curious. Constantly improving and sharing knowledge along the way.
url: https://greg.ee
baseurl: /
permalink: /:title
markdown: kramdown
highlighter: rouge
author: Greg Nesselmann
plugins:
  - jekyll-sitemap
