url: https://greg.ee
baseurl: /
title: All things web
tagline: Tinkering with the web
description: Web developer blog. Writing about my insights and experiences.
logo: logo.png
permalink: /:title
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  path: feed.xml

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
