url: https://greg.ee
baseurl: /
title: all things web
tagline: tinkering with the web
description: web developer blog. writing just about anything.
logo: logo.png
permalink: /:title
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  path: feed.xml

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
