title: greg's blog
tagline: tinkering with the web
description: tinkering with the web and writing about anything worthwhile
url: https://greg.ee
baseurl: /
logo: /favicon.webp
social:
  name: Greg Nesselmann
  links: 
    - https://github.com/gregness
    - https://www.linkedin.com/in/gregnesselmann
permalink: /:title
markdown: kramdown
image: /social-media.webp
author:
  name: Greg Nesselmann
  url: https://www.linkedin.com/in/gregnesselmann
highlighter: rouge
author: Greg Nesselmann
plugins:
  - jekyll-sitemap
  - jeyll-seo-tag
