url: https://greg.ee
baseurl: /
title: the greg's blog
tagline: you might find something interesting here
description: I am greg and this is my blog. it might just be that you find something interesting here!
logo: /logo.png
permalink: /:title
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  path: feed.xml

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
