url: "https://greg.ee"
baseurl: /
title: Greg's blog
tagline: Ramblings of a web developer
description: I am Greg and this is my blog. It might just be what you're' looking for!
logo: logo.png
permalink: /:title
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  path: feed.xml

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
